### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by KingKrex69** [Hex1629/HEX_CNC#1]
When I try to launch it, it crashes with this error.

```
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\HEX_CNC\HEX_CNC.py", line 16, in <module>
    {fg(70)}      ╦ ╦╔═╗═╗ ╦ {fg(70)}╔═╗╔╗╔╔═╗
     ^^^^^^
  File "C:\Users\PC\Desktop\HEX_CNC\HEX_CNC.py", line 13, in fg
    return Colored(name).foreground()
           ^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Roaming\Python\Python311\site-packages\colored\colored.py", line 48, in __init__
    self.enable_windows_terminal_mode()
  File "C:\Users\PC\AppData\Roaming\Python\Python311\site-packages\colored\colored.py", line 145, in enable_windows_terminal_mode
    ok = windll.kernel32.SetsConsoleMode(wintypes.HANDLE(hStdout), mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\ctypes\__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\ctypes\__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: function 'SetsConsoleMode' not found. Did you mean: 'GetConsoleMode'?
```

**Comment by KingKrex69** [comment]
> it not my error ( error from colored ) but if fix it use version 1.4.4

```
CONNECTION_TYPE=RAW PORT=1 SERVER RUNNING . . .
Exception in thread Thread-1 (CONFIG_CNC):
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\PC\Desktop\HEX_CNC\HEX_CNC.py", line 149, in CONFIG_CNC
    PATH = f'{os.path.join(os.path.dirname(__file__))}/assets/config.txt'
                                           ^^^^^^^^
NameError: name '__file__' is not defined. Did you mean: '__name__'?
```
